#!/usr/bin/python3
def raise_exception():
    1 + 'a'
